version: "3.5"
services:
    feegow-db:
        container_name: feegow-db
        image: mysql:8
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=f33G0wCh4ll3ng3
            - MYSQL_DATABASE=feegow-db
        volumes:
            - ./dump/feegow.sql:/docker-entrypoint-initdb.d/init.sql
            - persistent:/var/lib/mysql
        networks:
            - feegow-network
    feegow-app:
        container_name: feegow-app
        build: .
        ports: 
            - "8000:80"
        volumes:
            - .:/var/www/html/
        networks:
            - feegow-network
        depends_on:
            - feegow-db
        restart: on-failure
networks:
    feegow-network:
        name: feegow-network
volumes:
    persistent:
