version: '3.7'
services:
  app:
    build: './config/docker/php'
    ports:
      - 8081:8081
    networks:
      - link-banco
    volumes:
      - .:/app
    working_dir: /app
    container_name: feegow-challenge-app
  banco:
    image: mysql:5
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: feegow
      MYSQL_USER: feegow
      MYSQL_PASSWORD: senha_banco
      MYSQL_ROOT_PASSWORD: senha_root
    networks:
      - link-banco
    volumes:
      - ./var/data:/var/lib/mysql
networks:
  link-banco: