<div class="row">
    <div class="col-sm-12 text-center">
        <h2>Feegow challenge</h2>
    </div>
</div>

<div class="row d-flex justify-content-center">
    <div class="col-xl-8">
        <div class="card primary-color p-3">
            <form class="form-inline">
                <label class="white-text mx-xl-auto text-left">Consulta
                    de:</label>
                <div class="my-0 col-xl-6 px-0">
                    <select class="form-control w-100" id="specialities">
                        <option selected disabled value="0">--Selecione--
                        </option>
                    </select>
                </div>
                <button
                    class="btn btn-success btn-md my-2 my-sm-0 ml-auto btn-sm-block col-xl-2 mr-0"
                    type="button" id="search-professionals">Consultar</button>
            </form>
        </div>
    </div>
</div>

<div class="row d-flex justify-content-center my-3">
    <div class="col-xl-8">
        <p id="result-message"></p>
        <div class="row" id="result-cards"></div>
    </div>
</div>


<div class="row d-flex justify-content-center" >
    <div class="col-xl-8 d-none" id="form-consulta">
        <div class="card p-3">
            <h4 class="card-title mb-0"><b>Preecha seus dados:</b></h4>
            <hr />
            <form method="POST" action="/save-consulta" id="save-consulta">
                <div class="form-row">
                    <div class="form-group col-xl-6">
                        <label>Nome Completo</label>
                        <input type="text" class="form-control" name="name">
                    </div>
                    <div class="form-group col-xl-6">
                        <label>Como conheceu?</label>
                        <select class="form-control" id="sources" name="source_id">
                        </select>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-xl-6">
                        <label>Data de Nascimento</label>
                        <input type="date" class="form-control" name="birth_date">
                    </div>
                    <div class="form-group col-xl-6">
                        <label>CPF</label>
                        <input type="text" class="form-control cpf" name="cpf">
                    </div>
                </div>
                <hr />
                <button type="submit" class="btn btn-success float-right btn-sm">Salvar</button>
                <button type="button" class="btn btn-danger float-right btn-sm" id="cancel-consulta">Cancelar</button>
            </form>
        </div>
    </div>
</div>